{ lib }:
let
  inherit (lib) types isAttrs hasAttr;

  # Convert a Nix value to its KDL string representation
  toKDLValue = value:
    if builtins.isBool value then
      (if value then "true" else "false")
    else if builtins.isFloat value then
      builtins.toString value
    else if builtins.isInt value then
      builtins.toString value
    else if builtins.isString value then
      "\"${value}\""
    else if builtins.isList value then
      "[${lib.concatMapStringsSep " " toKDLValue value}]"
    else
      throw "Unsupported KDL value type: ${builtins.typeOf value}";

  # Check if a value is a "node" (attached with args)
  isKDLNode = v: isAttrs v && hasAttr "_node" v;

  # Render a single keybind binding to KDL
  renderBind = name: bind: let
    parts = lib.splitString "+" (lib.head (lib.splitString " " name));
    mods = lib.init parts;
    key = lib.last parts;
    actionStr = if builtins.isString bind.action then bind.action else throw "bind action must be string";
    argsStr = if builtins.hasAttr "args" bind && builtins.isList bind.args
              then " " + lib.concatMapStringsSep " " (a: "\"${a}\"") bind.args
              else "";
    allow-when-locked = if builtins.hasAttr "allow-when-locked" bind && bind.allow-when-locked then " allow-when-locked=true" else "";
    cooldown-ms = if builtins.hasAttr "cooldown-ms" bind then " cooldown-ms=${toString bind.cooldown-ms}" else "";
  in
    "bind ${lib.concatMapStringsSep " " (m: (if m == "Mod" then "Mod" else m)) mods} + ${key} { action=\"${actionStr}\"${argsStr};${allow-when-locked}${cooldown-ms}; }";

  # Render a window rule to KDL
  # Supports nested match attrs: { match = { app-id = "firefox"; }; open-maximized = true; }
  # For flat rules (no nested match), all non-special keys become match criteria
  renderWindowRule = rule: let
    action = rule.action or "set-window-rule";
    # Match criteria from nested match attr, or flat non-special keys
    matchAttrs = if builtins.hasAttr "match" rule && builtins.isAttrs rule.match
                 then rule.match
                 else builtins.removeAttrs rule ["action" "match"];
    # Properties: flat keys that aren't match, action, or special
    propAttrs = builtins.removeAttrs rule ["match" "action"];
    matchKeys = builtins.attrNames matchAttrs;
    propKeys = builtins.attrNames propAttrs;
    kdlVal = v:
      if builtins.isString v then "\"${v}\""
      else if builtins.isBool v then (if v then "true" else "false")
      else builtins.toString v;
    matchBlock = if matchKeys == [] then ""
      else "\n  match {\n${lib.concatMapStringsSep "\n" (k: "    ${k} ${kdlVal matchAttrs.${k}}") matchKeys}\n  }";
    propBlock = if propKeys == [] then ""
      else "\n${lib.concatMapStringsSep "\n" (k: "  ${k} ${kdlVal propAttrs.${k}}") propKeys}";
  in
    "window-rule {${matchBlock}${propBlock}\n}";

  # Render an attrset to KDL recursively
  renderAttrs = indent: prefix: attrs: let
    indentStr = lib.concatStringsSep "" (builtins.genList (_: "  ") indent);
  in lib.concatStringsSep "\n" (lib.flatten (lib.mapAttrsToList (name: value:
    if name == "_node" then [] else
    if name == "binds" && isAttrs value then
      lib.mapAttrsToList (bindName: bindVal: indentStr + renderBind bindName bindVal) value
    else if name == "windowRules" && builtins.isList value then
      map (rule: indentStr + renderWindowRule rule) value
    else if isAttrs value && !isKDLNode value then
      [ (indentStr + name + " {") (renderAttrs (indent + 1) (prefix + name + ".") value) (indentStr + "}") ]
    else if builtins.isList value then
      [ (indentStr + name + " " + toKDLValue value) ]
    else
      [ (indentStr + name + " " + toKDLValue value) ]
  ) attrs));

in {
  # Main entry point: take a Nix option tree and produce a KDL config string
  generate = niriConfig: let
    # Filter out meta keys (those starting with _)
    filtered = lib.filterAttrs (n: _: !(builtins.substring 0 1 n == "_")) niriConfig;
  in "# Niri configuration generated by INIR-NIX NixOS flake\n" +
     "# Manual changes will be overwritten on rebuild.\n\n" +
     renderAttrs 0 "" filtered + "\n";
}
