# Config generation snapshot test
# Run: nix eval --file nix/tests/snapshot.nix
{ lib, pkgs, ... }:
let
  # Import the config generators
  niriConfigGen = pkgs.callPackage ../niri-config.nix { };
  inirConfigGen = pkgs.callPackage ../inir-config.nix { };
  colorPipeline = import ../color-pipeline.nix { inherit lib; inputs = {}; };

  # Sample options to generate config from
  sampleOpts = {
    niri = {
      prefer-no-csd = true;
      layout = {
        gaps = 5;
        focus-ring = {
          width = 1.5;
          active-color = "#7fc8ff";
        };
      };
      binds = {
        "Mod+Return" = { action = "spawn"; args = [ "alacritty" ]; };
        "Mod+D" = { action = "spawn"; args = [ "fuzzel" ]; };
        "Mod+Q" = { action = "close-window"; };
      };
    };
  };

  # Generate configs
  generatedNiriKDL = niriConfigGen.generate sampleOpts.niri;

  # Expected KDL output (first few lines)
  expectedNiriKDL = ''
    # Niri configuration generated by INIR-NIX NixOS flake
    prefer-no-csd true
    layout {
      gaps 5
      focus-ring {
        width 1.5
        active-color "#7fc8ff"
      }
    }
    bind Mod + Return { action="spawn"; "alacritty"; }
    bind Mod + D { action="spawn"; "fuzzel"; }
    bind Mod + Q { action="close-window"; }
  '';

  # Dotfile source existence checks — verify all source paths resolve
  dotfileSources = {
    fishConfig = builtins.pathExists ../../dots/.config/fish/config.fish;
    fishAutoNiri = builtins.pathExists ../../dots/.config/fish/auto-Niri.fish;
    mpvConf = builtins.pathExists ../../dots/.config/mpv/mpv.conf;
    kvantumConfig = builtins.pathExists ../../dots/.config/Kvantum/kvantum.kvconfig;
    fontconfigConf = builtins.pathExists ../../dots/.config/fontconfig/fonts.conf;
    chromeFlags = builtins.pathExists ../../dots/.config/chrome-flags.conf;
    codeFlags = builtins.pathExists ../../dots/.config/code-flags.conf;
    vesktopThemes = builtins.pathExists ../../dots/.config/vesktop/themes;
    matugenDir = builtins.pathExists ../../dots/.config/matugen;
    portalsConf = builtins.pathExists ../../dots/.config/xdg-desktop-portal/niri-portals.conf;
    kdeglobals = builtins.pathExists ../../defaults/kde/kdeglobals;
    dolphinrc = builtins.pathExists ../../defaults/kde/dolphinrc;
    kservicemenurc = builtins.pathExists ../../defaults/kde/kservicemenurc;
    starshipToml = builtins.pathExists ../../defaults/starship/starship.toml;
    fuzzelIni = builtins.pathExists ../../defaults/fuzzel/fuzzel.ini;
    gtk3Settings = builtins.pathExists ../../defaults/gtk-3.0/settings.ini;
    gtk4Settings = builtins.pathExists ../../defaults/gtk-4.0/settings.ini;
    darklyrc = builtins.pathExists ../../dots/.config/darklyrc;
    konsolerc = builtins.pathExists ../../dots/.config/konsolerc;
    dolphinstaterc = builtins.pathExists ../../defaults/kde/dolphinstaterc;
    aiPrompts = builtins.pathExists ../../defaults/ai;
  };

  # Assert all sources exist
  dotfilesAllExist = lib.all (x: x) (builtins.attrValues dotfileSources);

in {
  niriConfigGenerated = generatedNiriKDL;
  niriConfigExpected = expectedNiriKDL;
  niriConfigMatch = builtins.match (builtins.replaceStrings [" "] [" "] generatedNiriKDL) (builtins.replaceStrings [" "] [" "] expectedNiriKDL);
  # For a real test, use a proper assertion:
  # niriConfigPass = assert (generatedNiriKDL == expectedNiriKDL); true;

  # Dotfile source verification
  inherit dotfileSources;
  dotfilesAllExist = assert dotfilesAllExist; true;
}
