# Config generation snapshot test
# Run: nix eval --file nix/tests/snapshot.nix
{ lib, pkgs, ... }:
let
  # Import the config generators
  niriConfigGen = pkgs.callPackage ../niri-config.nix { };
  inirConfigGen = pkgs.callPackage ../inir-config.nix { };
  colorPipeline = import ../color-pipeline.nix { inherit lib; inputs = {}; };

  # Sample options to generate config from
  sampleOpts = {
    niri = {
      prefer-no-csd = true;
      layout = {
        gaps = 5;
        focus-ring = {
          width = 1.5;
          active-color = "#7fc8ff";
        };
      };
      binds = {
        "Mod+Return" = { action = "spawn"; args = [ "alacritty" ]; };
        "Mod+D" = { action = "spawn"; args = [ "fuzzel" ]; };
        "Mod+Q" = { action = "close-window"; };
      };
    };
  };

  # Generate configs
  generatedNiriKDL = niriConfigGen.generate sampleOpts.niri;

  # Expected KDL output (first few lines)
  expectedNiriKDL = ''
    # Niri configuration generated by INIR-NIX NixOS flake
    prefer-no-csd true
    layout {
      gaps 5
      focus-ring {
        width 1.5
        active-color "#7fc8ff"
      }
    }
    bind Mod + Return { action="spawn"; "alacritty"; }
    bind Mod + D { action="spawn"; "fuzzel"; }
    bind Mod + Q { action="close-window"; }
  '';

in {
  niriConfigGenerated = generatedNiriKDL;
  niriConfigExpected = expectedNiriKDL;
  niriConfigMatch = builtins.match (builtins.replaceStrings [" "] [" "] generatedNiriKDL) (builtins.replaceStrings [" "] [" "] expectedNiriKDL);
  # For a real test, use a proper assertion:
  # niriConfigPass = assert (generatedNiriKDL == expectedNiriKDL); true;
}
